# Generated by Django 5.0.2 on 2024-02-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_band'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Title',
        ),
        migrations.AddField(
            model_name='listing',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
