# Generated by Django 5.0.2 on 2024-02-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_alter_listing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='fake',
            field=models.BooleanField(default=False),
        ),
    ]
